# Generated by Django 3.2 on 2021-07-26 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=3)),
                ('detail', models.TextField()),
                ('payment_intent', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 26, 17, 24, 23, 707975, tzinfo=utc))),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.place')),
            ],
        ),
    ]
