# Generated by Django 3.2 on 2021-07-26 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 17, 24, 47, 65135, tzinfo=utc)),
        ),
    ]
